language: elixir
elixir: 
  - 1.5.3
  - 1.7.2
otp_release: 
  - 20.2
  - 21.0
  
env:
 global:
   - MIX_ENV=test
script:
  - mix test
  - mix credo --strict

matrix:
  include:
    - elixir: 1.5.3
      otp_release: 20.2
    - elixir: 1.7.1
      otp_release: 21.0